# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{galetahub-auto_html}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Igor Galeta"]
  s.date = %q{2011-08-16}
  s.description = %q{Automatically transforms urls (via domain) and includes the destination resource (Vimeo, YouTube movie, image, ...) in your document}
  s.email = %q{galeta.igor@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENCE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "init.rb",
    "lib/auto_html.rb",
    "lib/auto_html/auto_html_for.rb",
    "lib/auto_html/base.rb",
    "lib/auto_html/builder.rb",
    "lib/auto_html/engine.rb",
    "lib/auto_html/filter.rb",
    "lib/auto_html/filters/big_words.rb",
    "lib/auto_html/filters/dailymotion.rb",
    "lib/auto_html/filters/google_video.rb",
    "lib/auto_html/filters/html_escape.rb",
    "lib/auto_html/filters/image.rb",
    "lib/auto_html/filters/link.rb",
    "lib/auto_html/filters/sanitize.rb",
    "lib/auto_html/filters/simple_format.rb",
    "lib/auto_html/filters/vimeo.rb",
    "lib/auto_html/filters/youtube.rb",
    "lib/auto_html/filters/youtube_js_api.rb",
    "test/fixture_setup.rb",
    "test/fixtures/database.yml",
    "test/fixtures/schema.rb",
    "test/functional/auto_html_for_options_test.rb",
    "test/functional/auto_html_for_test.rb",
    "test/test_helper.rb",
    "test/unit/auto_html_test.rb",
    "test/unit/filters/dailymotion_test.rb",
    "test/unit/filters/google_video_test.rb",
    "test/unit/filters/html_escape_test.rb",
    "test/unit/filters/image_test.rb",
    "test/unit/filters/link_test.rb",
    "test/unit/filters/sanitize_test.rb",
    "test/unit/filters/simple_format_test.rb",
    "test/unit/filters/vimeo_test.rb",
    "test/unit/filters/youtube_js_api_test.rb",
    "test/unit/filters/youtube_test.rb",
    "test/unit/unit_test_helper.rb"
  ]
  s.homepage = %q{https://github.com/galetahub/auto_html}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Automatically transforms urls (via domain) and includes the destination resource (Vimeo, YouTube movie, image, ...) in your document}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

